### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by Tudyx** [pauladam94/Ville-Embourb-e#1]
Please could you add a license to define how we can use this code?

**Comment by pauladam94** [comment]
I will do that

**Comment by pauladam94** [comment]
I am very curious, What do you want to use it for ? If you do it on github i will checkout what you have done 👌

**Comment by Tudyx** [comment]
Thanks for adding a license! We have done a small state of the art about what was available to do graph visualization with egui and then we opted for developing our own solution.

**Comment by pauladam94** [comment]
I think it's indeed the way intended if you use Egui. It's pretty much done for doing things yourself, specific for your job.
